In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

## HANDLING MISSING VALUE USING SKLEARN

In [2]:
df = pd.read_csv(r'messy_data_for_cleaning.csv')
df.head(3)

,ID,Name,Age,Salary,Email,Join_Date,Department,Performance_Score,Comments
0,524,Sarah Jones,41,60945,tom.taylor@gmail.com,2020-09-23,Engineering,1,Team player
1,603,Sarah Smith,56,63708,lisa.smith@gmail.com,2020-10-26,HR,3,Good employee
2,527,john jones,64,108059,emma.smith@hotmail.com,NaN,Engineering,1,Needs training in Python and SQL

In [3]:
df.shape

(1020, 9)

In [4]:
df.isnull().sum()

ID                     0
Name                  51
Age                   40
Salary                31
Email                 48
Join_Date             41
Department            25
Performance_Score     45
Comments             146
dtype: int64

In [5]:
(df.isnull().sum() * 100) / df.shape[0]

ID                    0.000000
Name                  5.000000
Age                   3.921569
Salary                3.039216
Email                 4.705882
Join_Date             4.019608
Department            2.450980
Performance_Score     4.411765
Comments             14.313725
dtype: float64

In [6]:
df.isnull().sum().sum()

np.int64(427)

In [7]:
(df.isnull().sum().sum() * 100) / (df.shape[0] * df.shape[1])

np.float64(4.651416122004357)

In [8]:
df.dtypes

ID                    int64
Name                 object
Age                  object
Salary               object
Email                object
Join_Date            object
Department           object
Performance_Score    object
Comments             object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 1020 non-null   int64
 1   Name               969 non-null    object
 2   Age                980 non-null    object
 3   Salary             989 non-null    object
 4   Email              972 non-null    object
 5   Join_Date          979 non-null    object
 6   Department         995 non-null    object
 7   Performance_Score  975 non-null    object
 8   Comments           874 non-null    object
dtypes: int64(1), object(8)
memory usage: 71.8+ KB

In [10]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy = 'most_frequent')

In [11]:
col = df.select_dtypes(object).columns
col

Index(['Name', 'Age', 'Salary', 'Email', 'Join_Date', 'Department',
       'Performance_Score', 'Comments'],
      dtype='object')

In [12]:
arr = si.fit_transform(df[col])
obj_df = pd.DataFrame(arr, columns = col)

In [15]:
obj_df.head()

,Name,Age,Salary,Email,Join_Date,Department,Performance_Score,Comments
0,Sarah Jones,41,60945,tom.taylor@gmail.com,2020-09-23,Engineering,1,Team player
1,Sarah Smith,56,63708,lisa.smith@gmail.com,2020-10-26,HR,3,Good employee
2,john jones,64,108059,emma.smith@hotmail.com,2018-09-08,Engineering,1,Needs training in Python and SQL
3,Emma Khan,50,98506,sarah.wilson@outlook.com,08-15-2016,Engineering,3,Needs training in Python and SQL
4,Emma Khan,21,106812,chris.taylor@hotmail.com,2018-09-08,Marketing,1,Excellent performer!!!!

In [13]:
obj_df.isnull().sum()

Name                 0
Age                  0
Salary               0
Email                0
Join_Date            0
Department           0
Performance_Score    0
Comments             0
dtype: int64