In [1]:
import pandas as pd

In [5]:
df = pd.DataFrame({'Size' : ['L', 'S', 'xL', 'M', 'M', 'L', 'xL', 'S', 'M', 'xS']})

In [6]:
df

  Size
0    L
1    S
2   xL
3    M
4    M
5    L
6   xL
7    S
8    M
9   xS

## Encosing using skLearn

In [31]:
ord_unique = [['xS', 'S', 'M', 'L', 'xL']]

In [32]:
ord_unique

[['xS', 'S', 'M', 'L', 'xL']]

In [36]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories = ord_unique)

df['sk_encoded'] = oe.fit_transform(df[['Size']]).astype(int)

In [37]:
df

  Size  sk_encoded
0    L           3
1    S           1
2   xL           4
3    M           2
4    M           2
5    L           3
6   xL           4
7    S           1
8    M           2
9   xS           0

## Encosing using map()

In [42]:
ord_unique = {
    'xS' : 0,
    'S' : 1,
    'M' : 2,
    'L' : 3,
    'xL' : 4,
}

df['map_encoded'] = df['Size'].map((ord_unique))

In [43]:
df

  Size  sk_encoded  map_encoded
0    L           3            3
1    S           1            1
2   xL           4            4
3    M           2            2
4    M           2            2
5    L           3            3
6   xL           4            4
7    S           1            1
8    M           2            2
9   xS           0            0